/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    HeaderToolBar: typeof import('./src/components/HeaderToolBar.vue')['default']
    LeftSiderMenu: typeof import('./src/components/LeftSiderMenu.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MainFrame: typeof import('./src/components/MainFrame.vue')['default']
    RightSiderProp: typeof import('./src/components/RightSiderProp.vue')['default']
    TestModule: typeof import('./src/components/TestModule.vue')['default']
  }
}
