/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CanvasHeaderToolBar: typeof import('./src/components/system_mode/canvas_mode/CanvasHeaderToolBar.vue')['default']
    CanvasMode: typeof import('./src/components/system_mode/canvas_mode/CanvasMode.vue')['default']
    EditMode: typeof import('./src/components/system_mode/edit_mode/EditMode.vue')['default']
    HeaderToolBar: typeof import('./src/components/system_mode/edit_mode/HeaderToolBar.vue')['default']
    LeftCanvasList: typeof import('./src/components/system_mode/canvas_mode/LeftCanvasList.vue')['default']
    LeftSiderMenu: typeof import('./src/components/system_mode/edit_mode/LeftSiderMenu.vue')['default']
    LogPanel: typeof import('./src/components/right_sider/LogPanel.vue')['default']
    MainCanvas: typeof import('./src/components/system_mode/canvas_mode/MainCanvas.vue')['default']
    MainContent: typeof import('./src/components/system_mode/edit_mode/MainContent.vue')['default']
    MainFrame: typeof import('./src/components/MainFrame.vue')['default']
    ModuleList: typeof import('./src/components/right_sider/ModuleList.vue')['default']
    PropPage: typeof import('./src/components/right_sider/PropPage.vue')['default']
    RightSider: typeof import('./src/components/RightSider.vue')['default']
    TestModuleCard: typeof import('./src/components/TestModuleCard.vue')['default']
    WidgetWrapper: typeof import('./src/components/system_mode/canvas_mode/WidgetWrapper.vue')['default']
  }
}
