/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ATag: typeof import('ant-design-vue/es')['Tag']
    HeaderToolBar: typeof import('./src/components/HeaderToolBar.vue')['default']
    LeftSiderMenu: typeof import('./src/components/LeftSiderMenu.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MainFrame: typeof import('./src/components/MainFrame.vue')['default']
    ModuleList: typeof import('./src/components/right_sider/ModuleList.vue')['default']
    PropPage: typeof import('./src/components/right_sider/PropPage.vue')['default']
    RightSider: typeof import('./src/components/RightSider.vue')['default']
    TestModuleCard: typeof import('./src/components/TestModuleCard.vue')['default']
  }
}
