// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bsd_testtool} from '../models';

export function CloseSerialPort():Promise<void>;

export function CreateApp(arg1:bsd_testtool.AppConfigSettings):Promise<void>;

export function CreateCanvas(arg1:bsd_testtool.CanvasConfig):Promise<void>;

export function DeleteApp(arg1:string):Promise<void>;

export function DeleteCanvas(arg1:string):Promise<void>;

export function DoStep():Promise<void>;

export function GetActionList():Promise<Array<bsd_testtool.ConfigActionBaseJson>>;

export function GetAllAppName():Promise<Array<string>>;

export function GetAllCalcFn():Promise<Array<string>>;

export function GetAllCanvasName():Promise<Array<string>>;

export function GetAllSerial():Promise<Array<string>>;

export function GetAppSettings():Promise<bsd_testtool.AppConfigSettings>;

export function GetCanvasData():Promise<bsd_testtool.CanvasConfig>;

export function GetNowApp():Promise<bsd_testtool.App>;

export function Init(arg1:string,arg2:string):Promise<void>;

export function InitReadApps(arg1:string):Promise<void>;

export function InitReadCanvas(arg1:string):Promise<void>;

export function LoadApp(arg1:string):Promise<void>;

export function LoadCanvas(arg1:string):Promise<void>;

export function OpenSerialPort():Promise<void>;

export function SaveApp():Promise<void>;

export function SaveCanvas(arg1:bsd_testtool.CanvasConfig):Promise<void>;

export function SelectSerialCom(arg1:string):Promise<void>;

export function Start():Promise<void>;

export function StartCanvasApp(arg1:string):Promise<void>;

export function StepStart():Promise<void>;

export function Stop():Promise<void>;

export function SyncActions(arg1:Array<bsd_testtool.ConfigActionBaseJson>):Promise<void>;

export function SyncAppSettings(arg1:bsd_testtool.AppConfigSettings):Promise<void>;
