// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bsd_testtool} from '../models';

export function CreateApp(arg1:bsd_testtool.AppConfigSettings):Promise<void>;

export function DeleteApp(arg1:string):Promise<void>;

export function GetActionList():Promise<Array<bsd_testtool.ConfigActionBaseJson>>;

export function GetAllAppName():Promise<Array<string>>;

export function GetAppSettings():Promise<bsd_testtool.AppConfigSettings>;

export function GetNowApp():Promise<bsd_testtool.App>;

export function Init(arg1:string):Promise<void>;

export function LoadApp(arg1:string):Promise<void>;

export function SaveApp():Promise<void>;

export function SyncActions(arg1:Array<bsd_testtool.ConfigActionBaseJson>):Promise<void>;

export function SyncAppSettings(arg1:bsd_testtool.AppConfigSettings):Promise<void>;
