// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['CreateApp'](arg1);
}

export function DeleteApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['DeleteApp'](arg1);
}

export function DoStep() {
  return window['go']['bsd_testtool']['Manager']['DoStep']();
}

export function GetActionList() {
  return window['go']['bsd_testtool']['Manager']['GetActionList']();
}

export function GetAllAppName() {
  return window['go']['bsd_testtool']['Manager']['GetAllAppName']();
}

export function GetAllCalcFn() {
  return window['go']['bsd_testtool']['Manager']['GetAllCalcFn']();
}

export function GetAllSerial() {
  return window['go']['bsd_testtool']['Manager']['GetAllSerial']();
}

export function GetAppSettings() {
  return window['go']['bsd_testtool']['Manager']['GetAppSettings']();
}

export function GetNowApp() {
  return window['go']['bsd_testtool']['Manager']['GetNowApp']();
}

export function Init(arg1) {
  return window['go']['bsd_testtool']['Manager']['Init'](arg1);
}

export function LoadApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['LoadApp'](arg1);
}

export function SaveApp() {
  return window['go']['bsd_testtool']['Manager']['SaveApp']();
}

export function SelectSerialCom(arg1) {
  return window['go']['bsd_testtool']['Manager']['SelectSerialCom'](arg1);
}

export function Start() {
  return window['go']['bsd_testtool']['Manager']['Start']();
}

export function StepStart() {
  return window['go']['bsd_testtool']['Manager']['StepStart']();
}

export function Stop() {
  return window['go']['bsd_testtool']['Manager']['Stop']();
}

export function SyncActions(arg1) {
  return window['go']['bsd_testtool']['Manager']['SyncActions'](arg1);
}

export function SyncAppSettings(arg1) {
  return window['go']['bsd_testtool']['Manager']['SyncAppSettings'](arg1);
}
