// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['CreateApp'](arg1);
}

export function DeleteApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['DeleteApp'](arg1);
}

export function GetActionList() {
  return window['go']['bsd_testtool']['Manager']['GetActionList']();
}

export function GetAllAppName() {
  return window['go']['bsd_testtool']['Manager']['GetAllAppName']();
}

export function GetAppSettings() {
  return window['go']['bsd_testtool']['Manager']['GetAppSettings']();
}

export function GetNowApp() {
  return window['go']['bsd_testtool']['Manager']['GetNowApp']();
}

export function Init(arg1) {
  return window['go']['bsd_testtool']['Manager']['Init'](arg1);
}

export function LoadApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['LoadApp'](arg1);
}

export function SaveApp() {
  return window['go']['bsd_testtool']['Manager']['SaveApp']();
}

export function SyncActions(arg1) {
  return window['go']['bsd_testtool']['Manager']['SyncActions'](arg1);
}

export function SyncAppSettings(arg1) {
  return window['go']['bsd_testtool']['Manager']['SyncAppSettings'](arg1);
}
