// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSerialPort() {
  return window['go']['bsd_testtool']['Manager']['CloseSerialPort']();
}

export function CreateApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['CreateApp'](arg1);
}

export function CreateCanvas(arg1) {
  return window['go']['bsd_testtool']['Manager']['CreateCanvas'](arg1);
}

export function DeleteApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['DeleteApp'](arg1);
}

export function DeleteCanvas(arg1) {
  return window['go']['bsd_testtool']['Manager']['DeleteCanvas'](arg1);
}

export function DoStep() {
  return window['go']['bsd_testtool']['Manager']['DoStep']();
}

export function ExportViewer() {
  return window['go']['bsd_testtool']['Manager']['ExportViewer']();
}

export function GetActionList() {
  return window['go']['bsd_testtool']['Manager']['GetActionList']();
}

export function GetAllAppName() {
  return window['go']['bsd_testtool']['Manager']['GetAllAppName']();
}

export function GetAllCalcFn() {
  return window['go']['bsd_testtool']['Manager']['GetAllCalcFn']();
}

export function GetAllCanvasName() {
  return window['go']['bsd_testtool']['Manager']['GetAllCanvasName']();
}

export function GetAllSerial() {
  return window['go']['bsd_testtool']['Manager']['GetAllSerial']();
}

export function GetAppSettings() {
  return window['go']['bsd_testtool']['Manager']['GetAppSettings']();
}

export function GetCanvasData() {
  return window['go']['bsd_testtool']['Manager']['GetCanvasData']();
}

export function GetNowApp() {
  return window['go']['bsd_testtool']['Manager']['GetNowApp']();
}

export function Init(arg1, arg2) {
  return window['go']['bsd_testtool']['Manager']['Init'](arg1, arg2);
}

export function InitReadApps(arg1) {
  return window['go']['bsd_testtool']['Manager']['InitReadApps'](arg1);
}

export function InitReadCanvas(arg1) {
  return window['go']['bsd_testtool']['Manager']['InitReadCanvas'](arg1);
}

export function LoadApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['LoadApp'](arg1);
}

export function LoadCanvas(arg1) {
  return window['go']['bsd_testtool']['Manager']['LoadCanvas'](arg1);
}

export function OpenSerialPort() {
  return window['go']['bsd_testtool']['Manager']['OpenSerialPort']();
}

export function SaveApp() {
  return window['go']['bsd_testtool']['Manager']['SaveApp']();
}

export function SaveCanvas(arg1) {
  return window['go']['bsd_testtool']['Manager']['SaveCanvas'](arg1);
}

export function SelectSerialCom(arg1) {
  return window['go']['bsd_testtool']['Manager']['SelectSerialCom'](arg1);
}

export function Start() {
  return window['go']['bsd_testtool']['Manager']['Start']();
}

export function StartCanvasApp(arg1) {
  return window['go']['bsd_testtool']['Manager']['StartCanvasApp'](arg1);
}

export function StepStart() {
  return window['go']['bsd_testtool']['Manager']['StepStart']();
}

export function Stop() {
  return window['go']['bsd_testtool']['Manager']['Stop']();
}

export function SyncActions(arg1) {
  return window['go']['bsd_testtool']['Manager']['SyncActions'](arg1);
}

export function SyncAppSettings(arg1) {
  return window['go']['bsd_testtool']['Manager']['SyncAppSettings'](arg1);
}
